apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugay-testwebapi
  labels:
    app: bugay-testwebapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bugay-testwebapi
  template:
    metadata:
      labels:
        app: bugay-testwebapi
    spec:
      containers:
      - name: bugay-testwebapi
        image: ${ACR_LOGIN_SERVER}/bugay-testwebapi:${IMAGE_TAG}
        ports:
        - containerPort: 5028
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
